---
- name: Configuracion de servidor NFS
  hosts: centos
  become: yes

  vars:
    nfs_compartido: /var/nfs_shared

  tasks:
    - name: Instalar NFS
      ansible.builtin.yum:
        name: nfs-utils
        state: present

    - name: Habilitar e iniciar servicio NFS
      ansible.builtin.service:
        name: nfs-server
        state: started
        enabled: yes

    - name: Permitir conexiones al puerto 2049
      ansible.posix.firewalld:
        port: 2049/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Crear directorio
      ansible.builtin.file:
        path: "{{ nfs_compartido }}"
        state: directory
        owner: nobody
        group: nobody
        mode: "0777"

    - name: Configurar export
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "{{ nfs_compartido }} *(rw,sync,no_subtree_check)"
      notify: Actualizar exports

  handlers:
    - name: Actualizar exports
      ansible.builtin.command: exportfs -r
